# Configuration Settings for ZED-F9P device

ublox_gps_node:
  ros__parameters:
    debug: 1                    # Range 0-4 (0 means no debug statements will print)
    save:
      mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver
                                # Manager, Antenna, and Logging Configuration
      device: 4                 # Save to EEPROM

    device: /dev/ttyACM0
    frame_id: gps_link
    rate: 1.0                     # in Hz
    nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may
                                # be either 5 Hz (Dual constellation) or
                                # 8 Hz (GPS only)
    dynamic_model: stationary    # Airborne < 2G, 2D fix not supported (3D only),
                                # Max Alt: 50km
                                # Max Horizontal Velocity: 250 m/s,
                                # Max Vertical Velocity: 100 m/s
    fix_mode: 2d
    enable_ppp: false
    dr_limit: 1

    tmode3: 0                   # Survey-In Mode disable
    uart1:
      baudrate: 115200           # NEO-M8U specific

    dgnss_mode: 3                # Fixed mode
    nmea:
      high_prec: true

    inf:
      all: true                  # Whether to display all INF messages in console

    gnss:
      glonass: true              # Supported by NEO-M8U
      galileo: true
      beidou: true              # Supported by NEO-M8U
      qzss: true
      qzss_sig_cfg: false

    publish:
      nav:
        pvt: true
      rxm:
        rtcm: true
